# calqlatr Page Object Definitions
# encoding: UTF-8
# Generated from: calqlatr.xml
# Generated by: Squish MCP POM Generator

from objectmaphelper import *
# Main application container
Calqlatr_Main = {"title": "Calqlatr", "type": "Main", "unnamed": 1, "visible": True}

# calqlatr page objects
Calqlatr_display_Display = {"container": Calqlatr_Main, "id": "display", "type": "Display", "unnamed": 1, "visible": True}
Calqlatr_numberPad_NumberPad = {"container": Calqlatr_Main, "id": "numberPad", "type": "NumberPad", "unnamed": 1, "visible": True}
Calqlatr_inputText_Text = {"container": Calqlatr_display_Display, "id": "inputText", "text": "7", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_lastEquationText_Text = {"container": Calqlatr_display_Display, "id": "lastEquationText", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_10 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 10, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_11 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 11, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_12 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 12, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_13 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 13, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_14 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 14, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_15 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 15, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_2 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_3 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 3, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_4 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 4, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_5 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 5, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_6 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 6, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_7 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 7, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_8 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 8, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_background_Rectangle_9 = {"container": Calqlatr_numberPad_NumberPad, "id": "background", "occurrence": 9, "type": "Rectangle", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "text": "7", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_10 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 10, "text": "2", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_11 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 11, "text": "3", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_12 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 12, "text": "-", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_13 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 13, "text": "0", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_14 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 14, "text": "=", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_15 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 15, "text": "+", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_2 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 2, "text": "8", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_3 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 3, "text": "9", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_4 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 4, "text": "/", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_5 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 5, "text": "4", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_6 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 6, "text": "5", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_7 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 7, "text": "6", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_8 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 8, "text": "*", "type": "Text", "unnamed": 1, "visible": True}
Calqlatr_contentItem_Text_9 = {"container": Calqlatr_numberPad_NumberPad, "id": "contentItem", "occurrence": 9, "text": "1", "type": "Text", "unnamed": 1, "visible": True}